package component:my-project;

/// An example world for the component to target.
world my-project {
    export register-routes: func();
    export load-from-ledger: func(cmd: string);
    export insert-in-ledger: func(cmd: string);
}
